"""Load Pulsecast exclusively from published NDMA county bulletins.

County metadata is static reference information; every drought phase, VCI3M,
SPI, source URL, and date is discovered from NDMA KnowledgeWeb at startup.
The service deliberately leaves the database without bulletin data when NDMA is
unavailable instead of manufacturing a replacement data set.
"""

import json
import logging
from datetime import datetime, timezone

from app.database import get_db, init_db
from app.services.calibration import compute_confidence_calibration
from app.services.forecast import generate_county_forecast
from app.services.historical_seed import expand_historical_records
from app.services.ingestion import ALL_COUNTIES, ingest_all_bulletins
from app.services.parser import parse_county_bulletin_with_ai_fallback
from app.services.patterns import (
    combine_pattern_signals,
    detect_recurrence_pattern,
    detect_regional_clusters,
)

logger = logging.getLogger(__name__)


async def build_pattern_signals(db) -> dict:
    """
    Compute cross-county/temporal pattern signals for every county in one
    pass (see app/services/patterns.py). Shared by both the batch
    regeneration path below and the single-county /regenerate endpoint,
    so a manual regenerate sees the same signals a full reseed would.

    Returns {county_id: pattern_signals_dict} — only for counties where
    at least one detector fired.
    """
    cursor = await db.execute("SELECT id, name, region FROM counties")
    counties = [dict(row) for row in await cursor.fetchall()]

    cursor = await db.execute(
        """SELECT county_id, month, phase FROM bulletins
           WHERE phase IS NOT NULL ORDER BY county_id, month ASC"""
    )
    all_bulletins = [dict(row) for row in await cursor.fetchall()]

    history_by_county: dict[int, list[dict]] = {}
    for row in all_bulletins:
        history_by_county.setdefault(row["county_id"], []).append(
            {"month": row["month"], "phase": row["phase"]}
        )

    # Regional clustering runs once over every county's latest bulletin.
    latest_by_county = []
    for county in counties:
        history = history_by_county.get(county["id"])
        if not history:
            continue
        latest_by_county.append({
            "county_id": county["id"],
            "county_name": county["name"],
            "region": county["region"],
            "phase": history[-1]["phase"],
        })
    clusters = detect_regional_clusters(latest_by_county)

    signals: dict[int, dict] = {}
    for county in counties:
        history = history_by_county.get(county["id"])
        recurrence = detect_recurrence_pattern(county["name"], history) if history else None
        cluster = clusters.get(county["id"])
        combined = combine_pattern_signals(recurrence, cluster)
        if combined:
            signals[county["id"]] = combined

    return signals


async def seed_database() -> None:
    """Load the latest official NDMA county-bulletin records into SQLite."""
    await init_db()

    # Fetch before opening a write transaction. The public NDMA endpoint can
    # take time to respond, and SQLite must not remain write-locked meanwhile.
    downloaded_bulletins = await ingest_all_bulletins()

    db = await get_db()
    try:
        for county in ALL_COUNTIES:
            await db.execute(
                """INSERT OR IGNORE INTO counties
                   (name, region, livelihood_zone, latitude, longitude)
                   VALUES (?, ?, ?, ?, ?)""",
                (
                    county["name"],
                    county["region"],
                    county["livelihood"],
                    county["lat"],
                    county["lon"],
                ),
            )
        await db.commit()

        # Remove only data generated by older versions of this application.
        # Published NDMA records are retained and updated from their canonical
        # source URL when a bulletin is reissued.
        await db.execute("DELETE FROM bulletins WHERE source_url = 'seeded-data'")
        await db.execute("DELETE FROM forecasts")

        cursor = await db.execute("SELECT id, name FROM counties")
        county_ids = {row["name"]: row["id"] for row in await cursor.fetchall()}

        # Real historical NDMA phase data (Sept 2022 - Feb 2026), found via
        # search since NDMA's own archive is gated behind a JS grid this
        # scraper can't crawl live — see historical_seed.py docstring. Never
        # overwrites a real live-parsed record for the same (county, month).
        backfilled = await _backfill_historical_data(db, county_ids)

        inserted_records = 0
        ai_recovered_records = 0
        parsed_at = datetime.now(timezone.utc).isoformat()
        for bulletin in downloaded_bulletins:
            record = await parse_county_bulletin_with_ai_fallback(
                bulletin["path"],
                bulletin["county_name"],
                bulletin["month"],
            )
            if not record:
                continue

            county_id = county_ids.get(record["county_name"])
            if county_id is None:
                logger.warning(
                    "Skipping NDMA record for county absent from metadata: %s",
                    record["county_name"],
                )
                continue

            if record["parsing_method"] == "ai_fallback":
                ai_recovered_records += 1

            await db.execute(
                """INSERT INTO bulletins
                   (county_id, month, vci3m, spi, phase, source_url, source_page,
                    parsed_at, parsing_method, ai_evidence)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                   ON CONFLICT(county_id, month) DO UPDATE SET
                       vci3m = excluded.vci3m,
                       spi = excluded.spi,
                       phase = excluded.phase,
                       source_url = excluded.source_url,
                       source_page = excluded.source_page,
                       parsed_at = excluded.parsed_at,
                       parsing_method = excluded.parsing_method,
                       ai_evidence = excluded.ai_evidence""",
                (
                    county_id,
                    record["month"],
                    record["vci3m"],
                    record["spi"],
                    record["phase"],
                    bulletin["url"],
                    record["source_page"],
                    parsed_at,
                    record["parsing_method"],
                    record["ai_evidence"],
                ),
            )
            inserted_records += 1

        await db.commit()

        if not inserted_records and not backfilled:
            cursor = await db.execute("SELECT COUNT(*) AS count FROM bulletins")
            existing_records = (await cursor.fetchone())["count"]
            if not existing_records:
                logger.warning(
                    "No NDMA bulletin records were parsed; no synthetic data was inserted."
                )
                return
            logger.warning(
                "No new NDMA records were parsed; regenerating forecasts from %s stored official records.",
                existing_records,
            )

        await _regenerate_forecasts(db)
        await db.commit()
        logger.info(
            "Loaded %s live NDMA bulletin records (%s recovered by AI parsing fallback) "
            "+ %s historical backfill records",
            inserted_records, ai_recovered_records, backfilled,
        )
    finally:
        await db.close()


async def _backfill_historical_data(db, county_ids: dict) -> int:
    """
    Insert real historical NDMA phase records (see historical_seed.py).
    Uses DO NOTHING on conflict — a real, live-parsed record for the same
    (county, month) always wins over this backfill; this only fills gaps.
    """
    parsed_at = datetime.now(timezone.utc).isoformat()
    records = expand_historical_records(ALL_COUNTIES)
    inserted = 0

    for record in records:
        county_id = county_ids.get(record["county_name"])
        if county_id is None:
            continue

        cursor = await db.execute(
            """INSERT INTO bulletins
               (county_id, month, vci3m, spi, phase, source_url, source_page, parsed_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?)
               ON CONFLICT(county_id, month) DO NOTHING""",
            (
                county_id,
                record["month"],
                record["vci3m"],
                record["spi"],
                record["phase"],
                record["source_url"],
                record["source_page"],
                parsed_at,
            ),
        )
        if cursor.rowcount:
            inserted += 1

    await db.commit()
    return inserted


async def _regenerate_forecasts(db) -> None:
    """Generate forecasts only from real, parsed VCI3M history."""
    cursor = await db.execute("SELECT id FROM counties")
    county_ids = [row["id"] for row in await cursor.fetchall()]

    # Computed once per run and reused for every county — this is a global
    # empirical hit-rate from backtesting the app's own past forecasts, not
    # a per-county figure. See app/services/calibration.py.
    calibration = await compute_confidence_calibration()

    # Cross-county/temporal pattern signals (recurrence + regional
    # clusters) — also computed once per run over every county's full
    # bulletin history. See app/services/patterns.py.
    pattern_signals_by_county = await build_pattern_signals(db)

    for county_id in county_ids:
        cursor = await db.execute(
            """SELECT vci3m, phase FROM bulletins
               WHERE county_id = ? AND vci3m IS NOT NULL
               ORDER BY month ASC""",
            (county_id,),
        )
        rows = await cursor.fetchall()
        if not rows:
            continue

        vci3m_series = [row["vci3m"] for row in rows]
        forecast = generate_county_forecast(
            county_id=county_id,
            historical_vci3m=vci3m_series,
            current_phase=rows[-1]["phase"],
            calibration=calibration,
            pattern_signals=pattern_signals_by_county.get(county_id),
        )
        await db.execute(
            """INSERT INTO forecasts
               (county_id, generated_at, forecast_weeks, forecast_values,
                crossing_date, crossing_phase, days_to_crossing,
                confidence, priority_score, pattern_signals)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                county_id,
                forecast["generated_at"],
                forecast["forecast_weeks"],
                json.dumps(forecast["forecast_values"]),
                forecast.get("crossing_date"),
                forecast.get("crossing_phase"),
                forecast.get("days_to_crossing"),
                forecast.get("confidence"),
                forecast.get("priority_score"),
                json.dumps(forecast["pattern_signals"]) if forecast.get("pattern_signals") else None,
            ),
        )


async def regenerate_forecasts() -> None:
    """Re-run forecasts from the currently stored official NDMA records."""
    db = await get_db()
    try:
        await db.execute("DELETE FROM forecasts")
        await _regenerate_forecasts(db)
        await db.commit()
    finally:
        await db.close()
