"""Load Pulsecast exclusively from published NDMA county bulletins.

County metadata is static reference information; every drought phase, VCI3M,
SPI, source URL, and date is discovered from NDMA KnowledgeWeb at startup.
The service deliberately leaves the database without bulletin data when NDMA is
unavailable instead of manufacturing a replacement data set.
"""

import json
import logging
from datetime import datetime, timezone

from app.database import get_db, init_db
from app.services.calibration import compute_confidence_calibration
from app.services.forecast import generate_county_forecast
from app.services.ingestion import ALL_COUNTIES, ingest_all_bulletins
from app.services.parser import parse_county_bulletin

logger = logging.getLogger(__name__)


async def seed_database() -> None:
    """Load the latest official NDMA county-bulletin records into SQLite."""
    await init_db()

    # Fetch before opening a write transaction. The public NDMA endpoint can
    # take time to respond, and SQLite must not remain write-locked meanwhile.
    downloaded_bulletins = await ingest_all_bulletins()

    db = await get_db()
    try:
        for county in ALL_COUNTIES:
            await db.execute(
                """INSERT OR IGNORE INTO counties
                   (name, region, livelihood_zone, latitude, longitude)
                   VALUES (?, ?, ?, ?, ?)""",
                (
                    county["name"],
                    county["region"],
                    county["livelihood"],
                    county["lat"],
                    county["lon"],
                ),
            )
        await db.commit()

        # Remove only data generated by older versions of this application.
        # Published NDMA records are retained and updated from their canonical
        # source URL when a bulletin is reissued.
        await db.execute("DELETE FROM bulletins WHERE source_url = 'seeded-data'")
        await db.execute("DELETE FROM forecasts")

        cursor = await db.execute("SELECT id, name FROM counties")
        county_ids = {row["name"]: row["id"] for row in await cursor.fetchall()}

        inserted_records = 0
        parsed_at = datetime.now(timezone.utc).isoformat()
        for bulletin in downloaded_bulletins:
            record = parse_county_bulletin(
                bulletin["path"],
                bulletin["county_name"],
                bulletin["month"],
            )
            if not record:
                continue

            county_id = county_ids.get(record["county_name"])
            if county_id is None:
                logger.warning(
                    "Skipping NDMA record for county absent from metadata: %s",
                    record["county_name"],
                )
                continue

            await db.execute(
                """INSERT INTO bulletins
                   (county_id, month, vci3m, spi, phase, source_url, source_page, parsed_at)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                   ON CONFLICT(county_id, month) DO UPDATE SET
                       vci3m = excluded.vci3m,
                       spi = excluded.spi,
                       phase = excluded.phase,
                       source_url = excluded.source_url,
                       source_page = excluded.source_page,
                       parsed_at = excluded.parsed_at""",
                (
                    county_id,
                    record["month"],
                    record["vci3m"],
                    record["spi"],
                    record["phase"],
                    bulletin["url"],
                    record["source_page"],
                    parsed_at,
                ),
            )
            inserted_records += 1

        await db.commit()

        if not inserted_records:
            cursor = await db.execute("SELECT COUNT(*) AS count FROM bulletins")
            existing_records = (await cursor.fetchone())["count"]
            if not existing_records:
                logger.warning(
                    "No NDMA bulletin records were parsed; no synthetic data was inserted."
                )
                return
            logger.warning(
                "No new NDMA records were parsed; regenerating forecasts from %s stored official records.",
                existing_records,
            )

        await _regenerate_forecasts(db)
        await db.commit()
        logger.info("Loaded %s official NDMA bulletin records", inserted_records)
    finally:
        await db.close()


async def _regenerate_forecasts(db) -> None:
    """Generate forecasts only from real, parsed VCI3M history."""
    cursor = await db.execute("SELECT id FROM counties")
    county_ids = [row["id"] for row in await cursor.fetchall()]

    # Computed once per run and reused for every county — this is a global
    # empirical hit-rate from backtesting the app's own past forecasts, not
    # a per-county figure. See app/services/calibration.py.
    calibration = await compute_confidence_calibration()

    for county_id in county_ids:
        cursor = await db.execute(
            """SELECT vci3m, phase FROM bulletins
               WHERE county_id = ? AND vci3m IS NOT NULL
               ORDER BY month ASC""",
            (county_id,),
        )
        rows = await cursor.fetchall()
        if not rows:
            continue

        vci3m_series = [row["vci3m"] for row in rows]
        forecast = generate_county_forecast(
            county_id=county_id,
            historical_vci3m=vci3m_series,
            current_phase=rows[-1]["phase"],
            calibration=calibration,
        )
        await db.execute(
            """INSERT INTO forecasts
               (county_id, generated_at, forecast_weeks, forecast_values,
                crossing_date, crossing_phase, days_to_crossing,
                confidence, priority_score)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                county_id,
                forecast["generated_at"],
                forecast["forecast_weeks"],
                json.dumps(forecast["forecast_values"]),
                forecast.get("crossing_date"),
                forecast.get("crossing_phase"),
                forecast.get("days_to_crossing"),
                forecast.get("confidence"),
                forecast.get("priority_score"),
            ),
        )


async def regenerate_forecasts() -> None:
    """Re-run forecasts from the currently stored official NDMA records."""
    db = await get_db()
    try:
        await db.execute("DELETE FROM forecasts")
        await _regenerate_forecasts(db)
        await db.commit()
    finally:
        await db.close()
